name: Appium CI
on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
  name: Appium Test
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Run Appium Server
        uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
